<html>
<style>
li{
	font-size: 11pt;
}
h3{
	text-align: center;
}
</style>
<h3>Find your next car through FindYourCarApp.</h3>
<br>
<ul>
<li>At FindYourCarApp you can make a decision on your next car using a variety of information that is present in our app.</li>
<br>
<li>We are collecting all the information about the dealers cars to make your buying process as easy as possible.</li>
<br>
<li>The app is designed to keep the entire search process as simple as possible.</li>
<br>
<li>We have reduced the hops that is needed to contact  a dealer.</li>
<br>
<li>Advanced filtering.</li>
<br>
<li>Save your favorite car.</li>
<br>
<li>Compare different model to make an informed decision before buying a car.</li>
<br>
<li>For feedback you can contact us as <a href="mailto:venkatesh@findyourcarapp.com">contact@findyourcarapp.com</a></li>
</ul>
</html>